apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod 
  namespace: ggckad-s2 
  labels:
    app: myapp
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - name: nginx1
    image: nginx
    securityContext: 
       runAsUser: 1000
  - name: nginx2
    image: nginx
    securityContext: 
       runAsUser: 2000
