apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ggckad-s5 
  labels:
    client: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: revproxy
  template:
    metadata:
      labels:
        app: revproxy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      restartPolicy: Always
