apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: try1
  name: try1
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/try1
spec:
  replicas: 3
  selector:
    matchLabels:
      run: try1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: try1
    spec:
      containers:
      - image: mirfanmcs/simpleapp
        volumeMounts:   #volume mount for configmap
        - name: car-vol
          mountPath: /etc/cars
        - name: hostvol
          mountPath: /tmp  #mapping /tmp from container. This will create the date.out in the host vol
        env:
        - name: ilike
          valueFrom:
            configMapKeyRef:
              name: colors
              key: favorite
        envFrom:
          - configMapRef:
              name: colors  
        #imagePullPolicy: Always
        name: try1
        readinessProbe:
          exec:
            command:
            - ls
            - /etc/cars     #ready when volume mounted
            #- cat
            #- /tmp/healthy
          periodSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: goproxy
        image: k8s.gcr.io/goproxy:0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - configMap:
           defaultMode: 420
           name: fast-car
        name: car-vol
      - name: hostvol
        hostPath:    #host path type volume
          path: /home/docker/vol #map to vol on host. In this case will map to the minikube. SSH to minikube 'minikube ssh' and create folder vol. date.out file will be created in this folder. 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
