apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
data:
  APPLICATION_SECRET_1: YXBwc2VjcmV0MQo=
  APPLICATION_SECRET_2: YXBwc2VjcmV0Mgo=

# Put the base64 encoded value in the secret.

# Please note that base64 encoding does not do any encryption, and anyone can easily decode it:
# It doesn't store in etcd as encrypted value. Future release of Kubernetes will have support of it.

# To encode run following command:
# $ echo appsecret1 | base64

# To decode run following command
#$ echo "YXBwc2VjcmV0MQo=" | base64 --decode

