apiVersion: v1
kind: Service
metadata:
  name: productservicesrv
  labels:
    run: productservicesrv
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: productserviceapp